# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYGfrb8WZRFqRS5thUqxmNhGnHDeCUCH
"""

print(dir(str))

a="hello world"
b=a.lower()
print(b)
c=a.upper()
print(c)

a="hello "
b=a.ljust(1)
print(b)

a="hello world"
b=a.split()
print(b)

a="hello world"
b=a.replace("h","j")
print(b)

a="hello world"
b=a.find("w")
print(b)

a='123'
b=a.isdigit()
print(b)

a="hello world"
b=a.count('w')
print(b)

r=range(10)
list_storage=list(r)
print(list_storage)

r=range(5,16,2)
list_storage=list(r)
print(list_storage)

def sum_no(num1,num2):
    return num1+num2

def sub_no(num1,num2):
    return num1-num2

def mul_no(num1,num2):
    return num1*num2

def div_no(num1,num2):
    return num1/num2
num1=384
num2=245
print(sum_no(num1,num2))
print(sub_no(num1,num2))
print(mul_no(num1,num2))
print(div_no(num1,num2))

def sum_no(num1=23,num2=6):
    return num1+num2
print(sum_no())

def sum_no(*args):
  total=sum(args)
  return total

print(sum_no(1,3,5))

add=lambda num1,num2:num1+num2
print(add(3,5))

def user(u_name,password):
  username="sonam"
  pass_w="sonam123@"
  if username==u_name and pass_w==password:
    print("user login")
  else:
    print("user not login")

u_name=str(input("enter user name"))
password=str(input("enter password"))
user(u_name,password)

"""ASSIGNMENT-4

"""

def sum_of(*args):
  total=sum(args)
  return total
def n_even(num):
  result=[]
  for i in range(1,num+1):
    if i%2==0:

      result.append(i)
  return result
num=int(input("Enter the number:"))
print("list of n even number",(n_even(num)))
print("sum:",sum_of(*n_even(num)))

