# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNsNf2TjK53H_ble7Awy76gtOg3vISYl
"""

import spacy
nlp=spacy.load('en_core_web_sm')

s=nlp("this is simple nlp. code to check spacy tool")
type(s)

for i in s:
  print(  i)

for i in s.sents:
  print(i)

"""stemming and lemmatization

"""

sen=nlp("this class is going and students are attending and hearing and they understanding the class")

for i in sen:
  print(f"{i} -{i.lemma_}")

for i in sen:
  print(f"{i}-{i.pos_}")

sen=nlp('apples are present in cafe of apple company')
from spacy import displacy
displacy.serve(sen,style='ent')

