# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4F2KqOGbKcm4EjuiEcOBrUtIw75I24A
"""

A=('A',)
print(A)

type(A)

A=('A')
print(A)

type(A)

dic={1:[1,2,3,4],2:"sonam mourya",3:(5,6,7)}
print(dic)
type(dic)

